[workspace]
resolver = "3"
members = [
    "oxidrop",
    "oxidrop-common",
    "oxidrop-ebpf",
]
default-members = ["oxidrop", "oxidrop-common"]

[workspace.package]
license = "GPLv2"
edition = "2024"

[workspace.dependencies]
aya = { version = "0.14.0", default-features = false }
aya-build = { version = "0.2.0", default-features = false }
aya-ebpf = { version = "0.2.1", default-features = false }
aya-log = { version = "0.3.0", default-features = false }
aya-log-ebpf = { version = "0.2.0", default-features = false }

anyhow = { version = "1", default-features = false }
cargo_metadata = { version = "0.23.0", default-features = false }
# `std` feature is currently required to build `clap`.
#
# See https://github.com/clap-rs/clap/blob/61f5ee5/clap_builder/src/lib.rs#L15.
clap = { version = "4.5.20", default-features = false, features = ["std","help","error-context","color"] }
libc = { version = "0.2.159", default-features = false }
tokio = { version = "1.40.0", default-features = false }
which = { version = "6.0.0", default-features = false }
network-types = "0.2.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["local-time"] }
axum = "0.8.9"
hyper = "1.10.1"
hyper-util = "0.1.20"

[profile.release.package.oxidrop-ebpf]
debug = 2
codegen-units = 1
strip = false

[workspace.lints.clippy]
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
must_use_candidate = "deny"

