[package]
name = "oxidrop"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
utoipa-axum = "0.2"
utoipa = { version = "5.5.0", features = ["axum_extras"] }
secrecy = { version = "0.10.3", features = ["serde"] }
axum-login = "0.18.0"
tower-sessions-redis-store = "0.16.0"
tower = "0.5.3"
oxidrop-common = { path = "../oxidrop-common", features = ["user"] }
tower-sessions = "0.14.0"
tower-http = { version = "0.7", features = ["fs","trace","catch-panic","timeout","limit","compression-gzip", "compression-br","cors"] }
clap = { version = "4.5.20", default-features = false, features = ["std","help","error-context","color","derive"] }
axum = {version = "0.8.9", features = ["http2", "ws"]}
hyper = "1.10.1"
hyper-util = "0.1.20"
tracing-subscriber = { version = "0.3.22", features = ["local-time"] }
rustix = { version = "1.1.4", features = ["time","linux_latest","net"] }
sqlx = { version = "0.9", features = [ "runtime-tokio","sqlite","derive","macros","migrate" ] }
thiserror = "2.0.20"
argon2 = "0.6"
bitflags = "2.13.1"
serde_json = "1.0.151"


serde = { workspace = true}
anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
tracing = { workspace = true }

[dev-dependencies]
etherparse = "0.21.0"
oxidrop-common = { path = "../oxidrop-common",features=["user"] }


[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
# TODO(https://github.com/rust-lang/cargo/issues/12375): this should be an artifact dependency, but
# it's not possible to tell cargo to use `-Z build-std` to build it. We cargo-in-cargo in the build
# script to build this, but we want to teach cargo about the dependency so that cache invalidation
# works properly.
#
# Note also that https://github.com/rust-lang/cargo/issues/10593 occurs when `target = ...` is added
# to an artifact dependency; it seems possible to work around that by setting `resolver = "1"` in
# Cargo.toml in the workspace root.
#
# Finally note that *any* usage of `artifact = ...` in *any* Cargo.toml in the workspace breaks
# workflows with stable cargo; stable cargo outright refuses to load manifests that use unstable
# features.
oxidrop-ebpf = { path = "../oxidrop-ebpf" }

[[bin]]
name = "oxidrop"
path = "src/main.rs"

[lints]
workspace = true
